# -*- coding: utf-8 -*-
"""projeto_coleta_de_dados_beautifulsoup4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zsXCVpqIKy64L0B6pLhGQxO18dDu-ELQ

**Extraindo dados do trending GitHub, 10 projetos mais populares**

**Pacotes utilizados:**

1.   requests
2.   beautifulsoup4
"""

import requests 

robots = requests.get('https://github.com/trending')

print(robots.status_code)

import requests
from requests.exceptions import HTTPError

def crawl_website(url: str) -> str:
 try:
   robots = requests.get(url)
   robots.raise_for_status()
 except HTTPError as exc:
   print(exc)
 else:
   return robots.text

URL = 'https://github.com/trending'
robots = crawl_website(url= URL)
print(robots)

URL = 'https://github.com/trending'

conteudo = crawl_website(URL)
with open(file='github.html', mode='w', encoding='utf8') as arquivo:
 arquivo.write(conteudo)

from bs4 import BeautifulSoup

pagina = BeautifulSoup(open('github.html', mode='r'), 'html.parser')
print(pagina)

projetos_github = []
ranking_atual = 1

for article in pagina.find_all('article')[:10]:
  ranking = ranking_atual
  ranking_atual += 1
  h1 = article.find('h1').get_text().strip().split('\n')
  nome_projeto = h1[2].strip()
  linguagem_span = article.find('span',{'itemprop': 'programmingLanguage'})
  linguagem = None if linguagem_span == None else linguagem_span.get_text()
  stars = int(article.find('a', {'class': 'Link--muted d-inline-block mr-3'}).get_text().strip().replace(',', ''))
  stars_today = int(article.find('span',{'class': 'd-inline-block float-sm-right'}).get_text().strip().replace('stars today', '').replace(',', ''))
  forks = int(article.find('a', {'class': 'Link--muted d-inline-block mr-3'}).find_next('a', {'class': 'Link--muted d-inline-block mr-3'}).get_text().strip().replace(',', ''))
  projeto = {
      'ranking': ranking,
      'project': nome_projeto,
      'language': linguagem,
      'stars': stars,
      'stars_today': stars_today,
      'forks': forks

  }
  projetos_github.append(projeto)

import csv 

cabecalho_github = ['ranking', 'project', 'language', 'stars', 'stars_today', 'forks']

with open('github.csv', 'w') as f:
        writer = csv.DictWriter(f, cabecalho_github)
        writer.writeheader()
        for elem in projetos_github:
            writer.writerow(elem)